version: '3.9'

services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # ilivalidatorws:
  #   image: sogis/ilivalidator-web-service:latest
  #   ports:
  #     - "8081:8080"
  #   expose:
  #     - 8080
  #   labels:
  #     - "traefik.http.services.ilivalidatorws.loadbalancer.server.port=8080"
  #     - "traefik.enable=true"
  #     # Specify http routing
  #     - "traefik.http.routers.ilivalidatorws.entrypoints=web"
  #     - "traefik.http.routers.ilivalidatorws.rule=Host('whoami.docker.localhost')"
  #     - "traefik.http.routers.ilivalidatorws.tls=false"

  ilivalidatorws:
    image: sogis/ilivalidator-web-service:latest
    environment:
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.ilivalidator-router.rule=PathPrefix(`/ilivalidator/`)"

      - "traefik.http.routers.ilivalidatorws.rule=PathPrefix(`/app`)"
      #- "traefik.http.middlewares.app-stripprefix.stripprefix.forceslash=true"
      #- "traefik.http.middlewares.app-stripprefix.stripprefix.prefixes=/app/"
      #- "traefik.http.routers.ilivalidatorws.middlewares=app-stripprefix"

      - "traefik.http.middlewares.ilivalidatorws.chain.middlewares=strip-prefix-1,strip-prefix-2"
      - "traefik.http.routers.ilivalidatorws.middlewares=ilivalidatorws"

      - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"
      - "traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+"


      # - traefik.http.middlewares.strip-prefix.chain.middlewares=strip-prefix-1,strip-prefix-2
      # - traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$
      # - traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=${1}/
      # - traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true
      # - traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+



      #- "traefik.http.routers.ilivalidator-router.service=ilivalidatorws"
      - "traefik.http.services.ilivalidatorws.loadbalancer.server.port=8080"
      #- "traefik.http.middlewares.ilivalidator-strip.stripprefix.prefixes=/ilivalidator"
      #- "traefik.http.middlewares.ilivalidator-strip.stripprefix.forceslash=false"
      #- "traefik.http.routers.ilivalidator-router.middlewares=ilivalidator-strip"

